resize on append
SeunginLyu/SoftSys-daalloc pull request #5
Opened 2019-02-27 23:41 UTC by MatthewBeaudouinLafon

Added resizing to append. Also checks to make sure that `max_size` doesn't get larger than the maximum int size. 

Also, we should consider changing `size` and `max_size` to an unsigned bit to double our maximum array length.

Diff looks bad because I fixed some comment spacing.

2019-03-01 20:03 UTC, labseven requested changes
okay once the two comments are adressed

2019-03-01 20:03 UTC, labseven commented on src/shvec.c
> +    int size;       // number of initialized values
Nice

2019-03-01 20:03 UTC, labseven commented on src/shvec.c
> +        int* old_data_ptr = shvec_array[id].data;
Can we split this off into a function shvec_expand(int id)?

2019-03-01 20:03 UTC, labseven commented on src/shvec.c
> +        while (shvec_array[id].size < shvec_array[id].max_size) {
Use global GROWTH_FACTOR for new max_size

2019-03-01 20:03 UTC, labseven commented on src/shvec.c
> +            if (shvec_array[id].max_size >= SHVEC_SIZE_CAP) {
Will this actually catch an overflow? if you overflow, max_size will become negative...

2019-03-01 20:04 UTC, labseven commented on src/shvec.c
> +            if (shvec_array[id].max_size >= SHVEC_SIZE_CAP) {
oh, I see, SHVEC_SIZE_CAP is one bit smaller than the largest int

2019-03-01 20:04 UTC, SeunginLyu commented on src/shvec.c
> +        int* old_data_ptr = shvec_array[id].data;
```suggestion
        int* old_data = shvec_array[id].data;
```

2019-03-05 19:28 UTC, labseven requested changes

2019-03-05 19:28 UTC, labseven commented on src/shvec.c
> +    while (shvec_array[id].size < shvec_array[id].max_size) {
either move line 52 into the while or get rid of the while.

This way, the while is redundant AND can have the program get stuck in an infinite loop

2019-03-05 19:28 UTC, labseven commented on src/shvec.h
> +int shvec_expand(int id);
I would not put this into the header, nobody outside should be calling this

2019-03-08 02:20 UTC, labseven approved these changes
Looks good

2019-03-08 02:20 UTC, merged